-- Total employed population of philosophy BA degree holders (1,3)
SELECT SUM(PWGTP::INTEGER) AS employed_ba_population
FROM "philosophy-5-year-public-microdata-sample-2023"
WHERE ESR IN ('1', '3')
AND WAGP::FLOAT > 0
AND SCHL = '21';

-- Philosophy BA holders + any graduate degree
SELECT SUM(PWGTP::INTEGER) AS est_population,
    ROUND(SUM(WAGP::FLOAT * PWGTP::FLOAT) / SUM(PWGTP::FLOAT), 0) AS weighted_avg_wage,
    MEDIAN(WAGP::INTEGER) AS median_wage
FROM "philosophy-5-year-public-microdata-sample-2023"
WHERE FOD1P = '6212'
AND ESR IN ('1', '3')
AND WAGP::FLOAT > 0
AND SCHL IN ('21', '22', '23', '24');

-- Grab occupation codes
CREATE TABLE occupation_codes (
    occp_code VARCHAR,
    occp_title VARCHAR
);

CREATE TABLE IF NOT EXISTS PUBLIC.occupation_labels (
    occp_code VARCHAR(4) PRIMARY KEY,
    occp_title VARCHAR(200)
);

INSERT INTO PUBLIC.occupation_labels (occp_code, occp_title) VALUES
-- Management Occupations
('0010', 'Chief executives'),
('0020', 'General and operations managers'),
('0040', 'Advertising and promotions managers'),
('0051', 'Marketing managers'),
('0052', 'Sales managers'),
('0060', 'Public relations and fundraising managers'),
('0101', 'Administrative services managers'),
('0102', 'Facilities managers'),
('0110', 'Computer and information systems managers'),
('0120', 'Financial managers'),
('0135', 'Compensation and benefits managers'),
('0136', 'Human resources managers'),
('0137', 'Training and development managers'),
('0140', 'Industrial production managers'),
('0150', 'Purchasing managers'),
('0160', 'Transportation, storage, and distribution managers'),
('0205', 'Farmers, ranchers, and other agricultural managers'),
('0220', 'Construction managers'),
('0230', 'Education and childcare administrators'),
('0300', 'Engineering managers'),
('0310', 'Food service managers'),
('0335', 'Entertainment and recreation managers'),
('0340', 'Lodging managers'),
('0350', 'Medical and health services managers'),
('0360', 'Natural sciences managers'),
('0410', 'Property, real estate, and community association managers'),
('0420', 'Social and community service managers'),
('0425', 'Emergency management directors'),
('0440', 'Managers, all other'),

-- Business and Financial Operations Occupations
('0500', 'Agents and business managers of artists, performers, and athletes'),
('0520', 'Wholesale and retail buyers, except farm products'),
('0530', 'Purchasing agents, except wholesale, retail, and farm products'),
('0540', 'Claims adjusters, appraisers, examiners, and investigators'),
('0565', 'Compliance officers'),
('0600', 'Cost estimators'),
('0630', 'Human resource workers'),
('0640', 'Compensation, benefits, and job analysis specialists'),
('0650', 'Training and development specialists'),
('0700', 'Logisticians'),
('0705', 'Project management specialists'),
('0710', 'Management analysts'),
('0725', 'Meeting, convention, and event planners'),
('0726', 'Fundraisers'),
('0735', 'Market research analysts and marketing specialists'),
('0750', 'Business operations specialists, all other'),
('0800', 'Accountants and auditors'),
('0810', 'Property appraisers and assessors'),
('0820', 'Budget analysts'),
('0830', 'Credit analysts'),
('0845', 'Financial and investment analysts'),
('0850', 'Personal financial advisors'),
('0860', 'Insurance underwriters'),
('0900', 'Financial examiners'),
('0910', 'Loan counselors and officers'),
('0930', 'Tax examiners, collectors, and revenue agents'),
('0940', 'Tax preparers'),
('0960', 'Other financial specialists'),

-- Computer and Mathematical Occupations
('1005', 'Computer and information research scientists'),
('1006', 'Computer systems analysts'),
('1007', 'Information security analysts'),
('1010', 'Computer programmers'),
('1021', 'Software developers'),
('1022', 'Software quality assurance analysts and testers'),
('1031', 'Web developers'),
('1032', 'Web or digital interface designers'),
('1050', 'Computer support specialists'),
('1065', 'Database administrators and architects'),
('1105', 'Network and computer systems administrators'),
('1106', 'Computer network architects'),
('1108', 'Computer occupations, all other'),
('1200', 'Actuaries'),
('1220', 'Operations research analysts'),
('1240', 'Other mathematical science occupations'),

-- Architecture and Engineering Occupations
('1305', 'Architects, except landscape and naval'),
('1310', 'Surveyors, cartographers, and photogrammetrists'),
('1320', 'Aerospace engineers'),
('1340', 'Agricultural and biomedical engineers'),
('1350', 'Chemical engineers'),
('1360', 'Civil engineers'),
('1400', 'Computer hardware engineers'),
('1410', 'Electrical and electronic engineers'),
('1420', 'Environmental engineers'),
('1430', 'Industrial engineers, including health and safety'),
('1440', 'Marine engineers and naval architects'),
('1450', 'Materials engineers'),
('1460', 'Mechanical engineers'),
('1520', 'Petroleum engineers'),
('1530', 'Engineers, all other'),
('1541', 'Architectural and civil drafters'),
('1545', 'Other drafters'),
('1551', 'Electrical and electronic engineering technologists and technicians'),
('1555', 'Other engineering technologists and technicians, except drafters'),
('1560', 'Surveying and mapping technicians'),

-- Life, Physical, and Social Science Occupations
('1610', 'Biological scientists'),
('1650', 'Medical scientists and life scientists, all other'),
('1720', 'Chemists and materials scientists'),
('1745', 'Environmental scientists and geoscientists'),
('1750', 'Physical scientists, all other'),
('1760', 'Physical scientists, all other'),
('1822', 'Psychologists'),
('1825', 'Psychologists, all other'),
('1840', 'Urban and regional planners'),
('1860', 'Miscellaneous social scientists, including survey researchers and sociologists'),
('1900', 'Agricultural and food science technicians'),
('1920', 'Chemical technicians'),
('1935', 'Geoscience and environmental science technicians'),
('1970', 'Other life, physical, and social science technicians'),
('1980', 'Occupational health and safety specialists and technicians'),

-- Community and Social Service Occupations
('2002', 'Educational, guidance, and career counselors and advisors'),
('2003', 'Marriage and family therapists'),
('2004', 'Mental health counselors'),
('2006', 'Counselors, all other'),
('2011', 'Child, family, and school social workers'),
('2012', 'Healthcare social workers'),
('2014', 'Social workers, all other'),
('2015', 'Probation officers and correctional treatment specialists'),
('2016', 'Social and human service assistants'),
('2025', 'Other community and social service specialists'),
('2040', 'Clergy'),
('2050', 'Directors, religious activities and education'),
('2060', 'Religious workers, all other'),

-- Legal Occupations
('2100', 'Lawyers'),
('2105', 'Judicial law clerks'),
('2145', 'Paralegals and legal assistants'),
('2170', 'Title examiners, abstractors, and searchers'),
('2180', 'Legal support workers, all other'),

-- Education, Instruction, and Library Occupations
('2205', 'Postsecondary teachers'),
('2300', 'Preschool and kindergarten teachers'),
('2310', 'Elementary and middle school teachers'),
('2320', 'Secondary school teachers'),
('2330', 'Special education teachers'),
('2350', 'Tutors and other teachers and instructors'),
('2360', 'Other teachers and instructors'),
('2435', 'Librarians and media collections specialists'),
('2440', 'Library technicians'),
('2545', 'Teacher assistants'),
('2555', 'Other educational instruction and library workers'),

-- Arts, Design, Entertainment, Sports, and Media Occupations
('2600', 'Artists and related workers'),
('2633', 'Floral designers'),
('2634', 'Graphic designers'),
('2635', 'Interior designers'),
('2636', 'Merchandise displayers and window trimmers'),
('2640', 'Other designers'),
('2700', 'Actors'),
('2710', 'Producers and directors'),
('2721', 'Athletes and sports competitors'),
('2722', 'Coaches and scouts'),
('2751', 'Music directors and composers'),
('2805', 'Broadcast announcers and radio disc jockeys'),
('2810', 'News analysts, reporters, and journalists'),
('2825', 'Public relations specialists'),
('2830', 'Editors'),
('2840', 'Technical writers'),
('2850', 'Writers and authors'),
('2861', 'Interpreters and translators'),
('2865', 'Media and communication workers, all other'),
('2905', 'Broadcast, sound, and lighting technicians'),
('2910', 'Photographers'),
('2920', 'Television, video, and film camera operators and editors'),

-- Healthcare Practitioners and Technical Occupations
('3000', 'Chiropractors'),
('3030', 'Dietitians and nutritionists'),
('3050', 'Pharmacists'),
('3110', 'Physician assistants'),
('3140', 'Audiologists'),
('3150', 'Occupational therapists'),
('3160', 'Physical therapists'),
('3220', 'Respiratory therapists'),
('3230', 'Speech-language pathologists'),
('3245', 'Exercise physiologists and therapists, all other'),
('3255', 'Registered nurses'),
('3258', 'Nurse practitioners'),
('3261', 'Acupuncturists'),
('3300', 'Clinical laboratory technologists and technicians'),
('3310', 'Dental hygienists'),
('3321', 'Cardiovascular technologists and technicians'),
('3322', 'Diagnostic medical sonographers'),
('3323', 'Radiologic technologists and technicians'),
('3324', 'Magnetic resonance imaging technologists'),
('3330', 'Nuclear medicine technologists and medical dosimetrists'),
('3401', 'Emergency medical technicians'),
('3402', 'Paramedics'),
('3421', 'Pharmacy technicians'),
('3422', 'Psychiatric technicians'),
('3423', 'Surgical technologists'),
('3500', 'Licensed practical and licensed vocational nurses'),
('3515', 'Medical records specialists'),
('3545', 'Miscellaneous health technologists and technicians'),
('3550', 'Other healthcare practitioners and technical occupations'),

-- Healthcare Support Occupations
('3601', 'Home health aides'),
('3602', 'Personal care aides'),
('3603', 'Nursing assistants'),
('3605', 'Orderlies and psychiatric aides'),
('3620', 'Physical therapist assistants and aides'),
('3640', 'Dental assistants'),
('3645', 'Medical assistants'),
('3646', 'Medical transcriptionists'),
('3649', 'Phlebotomists'),
('3655', 'Other healthcare support workers'),

-- Protective Service Occupations
('3700', 'First-line supervisors of correctional officers'),
('3710', 'First-line supervisors of police and detectives'),
('3720', 'First-line supervisors of firefighting and prevention workers'),
('3725', 'First-line supervisors of security workers'),
('3740', 'Firefighters'),
('3802', 'Correctional officers and jailers'),
('3820', 'Detectives and criminal investigators'),
('3870', 'Police officers'),
('3910', 'Private detectives and investigators'),
('3930', 'Security guards and gaming surveillance officers'),
('3940', 'Crossing guards and flaggers'),
('3945', 'Transportation security screeners'),
('3960', 'Other protective service workers'),

-- Food Preparation and Serving Occupations
('4000', 'Chefs and head cooks'),
('4010', 'First-line supervisors of food preparation and serving workers'),
('4020', 'Cooks'),
('4030', 'Food preparation workers'),
('4040', 'Bartenders'),
('4055', 'Fast food and counter workers'),
('4110', 'Waiters and waitresses'),
('4120', 'Food servers, non-restaurant'),
('4130', 'Dining room and cafeteria attendants and bartender helpers'),
('4140', 'Dishwashers'),
('4150', 'Hosts and hostesses, restaurant, lounge, and coffee shop'),

-- Building and Grounds Cleaning and Maintenance Occupations
('4200', 'First-line supervisors of housekeeping and janitorial workers'),
('4210', 'First-line supervisors of landscaping, lawn service, and grounds keeping workers'),
('4220', 'Janitors and building cleaners'),
('4230', 'Maids and housekeeping cleaners'),
('4240', 'Pest control workers'),
('4251', 'Landscaping and grounds keeping workers'),
('4252', 'Tree trimmers and pruners'),
('4255', 'Other grounds maintenance workers'),

-- Personal Care and Service Occupations
('4330', 'Supervisors of personal care and service workers'),
('4350', 'Animal caretakers'),
('4400', 'Gaming services workers'),
('4435', 'Other entertainment attendants and related workers'),
('4465', 'Morticians, undertakers, and funeral arrangers'),
('4510', 'Hairdressers, hairstylists, and cosmetologists'),
('4521', 'Manicurists and pedicurists'),
('4522', 'Skincare specialists'),
('4540', 'Tour and travel guides'),
('4600', 'Child care workers'),
('4621', 'Exercise trainers and group fitness instructors'),
('4622', 'Recreation workers'),
('4655', 'Personal care and service workers, all other'),

-- Sales and Related Occupations
('4700', 'First-line supervisors of retail sales workers'),
('4710', 'First-line supervisors of non-retail sales workers'),
('4720', 'Cashiers'),
('4740', 'Counter and rental clerks'),
('4750', 'Parts salespersons'),
('4760', 'Retail salespersons'),
('4800', 'Advertising sales agents'),
('4810', 'Insurance sales agents'),
('4820', 'Securities, commodities, and financial services sales agents'),
('4840', 'Sales representatives of services, except advertising, insurance, travel, and financial services'),
('4850', 'Sales representatives, wholesale and manufacturing'),
('4900', 'Models, demonstrators, and product promoters'),
('4920', 'Real estate brokers and sales agents'),
('4930', 'Sales engineers'),
('4950', 'Door-to-door sales workers, news and street vendors, and related workers'),
('4965', 'Sales and related workers, all other'),

-- Office and Administrative Support Occupations
('5000', 'First-line supervisors of office and administrative support workers'),
('5020', 'Telephone operators'),
('5100', 'Bill and account collectors'),
('5110', 'Billing and posting clerks'),
('5120', 'Bookkeeping, accounting, and auditing clerks'),
('5140', 'Payroll and timekeeping clerks'),
('5150', 'Procurement clerks'),
('5160', 'Tellers'),
('5165', 'Financial clerks, all other'),
('5220', 'Court, municipal, and license clerks'),
('5230', 'Credit authorizers, checkers, and clerks'),
('5240', 'Customer service representatives'),
('5250', 'Eligibility interviewers, government programs'),
('5260', 'File clerks'),
('5300', 'Hotel, motel, and resort desk clerks'),
('5310', 'Interviewers, except eligibility and loan'),
('5320', 'Library assistants, clerical'),
('5330', 'Loan interviewers and clerks'),
('5360', 'Human resources assistants, except payroll and timekeeping'),
('5400', 'Receptionists and information clerks'),
('5410', 'Reservation and transportation ticket agents and travel clerks'),
('5420', 'Information and record clerks, all other'),
('5510', 'Couriers and messengers'),
('5521', 'Public safety telecommunicators'),
('5522', 'Dispatchers, except police, fire, and ambulance'),
('5530', 'Meter readers, utilities'),
('5540', 'Postal service clerks'),
('5550', 'Postal service mail carriers'),
('5560', 'Postal service mail sorters, processors, and processing machine operators'),
('5600', 'Production, planning, and expediting clerks'),
('5610', 'Shipping, receiving, and inventory clerks'),
('5630', 'Weighers, measurers, checkers, and samplers, recordkeeping'),
('5710', 'Executive secretaries and executive administrative assistants'),
('5720', 'Legal secretaries and administrative assistants'),
('5740', 'Secretaries and administrative assistants, except legal, medical, and executive'),
('5810', 'Data entry keyers'),
('5820', 'Word processors and typists'),
('5840', 'Insurance claims and policy processing clerks'),
('5850', 'Mail clerks and mail machine operators, except postal service'),
('5860', 'Office clerks, general'),
('5900', 'Office machine operators, except computer'),
('5920', 'Statistical assistants'),
('5940', 'Office and administrative support workers, all other'),

-- Farming, Fishing, and Forestry Occupations
('6040', 'Graders and sorters, agricultural products'),
('6050', 'Miscellaneous agricultural workers'),
('6120', 'Forest and conservation workers'),

-- Construction and Extraction Occupations
('6200', 'First-line supervisors of construction trades and extraction workers'),
('6230', 'Carpenters'),
('6240', 'Carpet, floor, and tile installers and finishers'),
('6260', 'Construction laborers'),
('6355', 'Electricians'),
('6360', 'Glaziers'),
('6410', 'Painters and paperhangers'),
('6442', 'Plumbers, pipefitters, and steamfitters'),
('6520', 'Sheet metal workers'),
('6530', 'Structural iron and steel workers'),
('6540', 'Helpers, construction trades'),
('6660', 'Construction and building inspectors'),
('6765', 'Miscellaneous construction and related workers, including photovoltaic installers'),

-- Installation, Maintenance, and Repair Occupations
('7000', 'First-line supervisors of mechanics, installers, and repairers'),
('7010', 'Computer, automated teller, and office machine repairers'),
('7020', 'Radio and telecommunications equipment installers and repairers'),
('7040', 'Electric motor, power tool, and related repairers'),
('7100', 'Electrical and electronics repairers, industrial and utility'),
('7120', 'Electronic home entertainment equipment installers and repairers'),
('7130', 'Security and fire alarm systems installers'),
('7140', 'Aircraft mechanics and service technicians'),
('7200', 'Automotive service technicians and mechanics'),
('7210', 'Bus and truck mechanics and diesel engine specialists'),
('7220', 'Heavy vehicle and mobile equipment service technicians and mechanics'),
('7300', 'Control and valve installers and repairers'),
('7315', 'Heating, air conditioning, and refrigeration mechanics and installers'),
('7330', 'Industrial and refractory machinery mechanics'),
('7340', 'Maintenance and repair workers, general'),
('7360', 'Millwrights'),
('7420', 'Telecommunications line installers and repairers'),
('7430', 'Precision instrument and equipment repairers'),
('7640', 'Other installation, maintenance, and repair workers'),

-- Production Occupations
('7700', 'First-line supervisors of production and operating workers'),
('7720', 'Electrical, electronics, and electromechanical assemblers'),
('7750', 'Other assemblers and fabricators'),
('7800', 'Bakers'),
('7840', 'Food batchmakers'),
('7855', 'Food processing workers, all other'),
('7950', 'Cutting, punching, and press machine setters, operators, and tenders, metal and plastic'),
('8030', 'Machinists'),
('8100', 'Molders and molding machine setters, operators, and tenders, metal and plastic'),
('8140', 'Welding, soldering, and brazing workers'),
('8250', 'Prepress technicians and workers'),
('8256', 'Print binding and finishing workers'),
('8300', 'Laundry and dry-cleaning workers'),
('8320', 'Sewing machine operators'),
('8350', 'Tailors, dressmakers, and sewers'),
('8465', 'Other textile, apparel, and furnishings workers'),
('8600', 'Power plant operators, distributors, and dispatchers'),
('8610', 'Stationary engineers and boiler operators'),
('8620', 'Water and liquid waste treatment plant and system operators'),
('8710', 'Cutting workers'),
('8740', 'Inspectors, testers, sorters, samplers, and weighers'),
('8750', 'Jewelers and precious stone and metal workers'),
('8800', 'Packaging and filling machine operators and tenders'),
('8810', 'Painting workers'),
('8830', 'Photographic process workers and processing machine operators'),
('8920', 'Molders, shapers, and casters, except metal and plastic'),
('8990', 'Other production workers'),

-- Transportation and Material Moving Occupations
('9005', 'Supervisors of transportation and material moving workers'),
('9030', 'Aircraft pilots and flight engineers'),
('9040', 'Air traffic controllers and airfield operations specialists'),
('9050', 'Flight attendants'),
('9121', 'Bus drivers, school'),
('9122', 'Bus drivers, transit and intercity'),
('9130', 'Driver/sales workers and truck drivers'),
('9141', 'Shuttle drivers and chauffeurs'),
('9142', 'Taxi drivers'),
('9150', 'Motor vehicle operators, all other'),
('9365', 'Transportation service attendants'),
('9410', 'Transportation inspectors'),
('9430', 'Other transportation workers'),
('9600', 'Industrial truck and tractor operators'),
('9610', 'Cleaners of vehicles and equipment'),
('9620', 'Laborers and freight, stock, and material movers, hand'),
('9640', 'Packers and packagers, hand'),
('9645', 'Stockers and order fillers'),
('9760', 'Other material moving workers');
